export const FETCH_IMAGE_GALLERY_SUCCESS='FETCH_IMAGE_GALLERY_SUCCESS';
export const FETCH_IMAGE_GALLERY_FAILURE='FETCH_IMAGE_GALLERY_FAILURE';
export const ADD_FAVOURITE_IMAGE='ADD_FAVOURITE_IMAGE';
export const REMOVE_FAVOURITE='REMOVE_FAVOURITE';