export const FETCH_IMAGE_GALLERY='FETCH_IMAGE_GALLERY';
export const FETCH_IMAGE_GALLERY_SUCCESS='FETCH_IMAGE_GALLERY_SUCCESS';
export const FETCH_IMAGE_GALLERY_FAILURE='FETCH_IMAGE_GALLERY_FAILURE';
export const ADD_FAVOURITE_IMAGE='ADD_FAVOURITE_IMAGE';
export const ADD_FAVOURITE_IMAGE_SAGA='ADD_FAVOURITE_IMAGE_SAGA';
export const REMOVE_FAVOURITE='REMOVE_FAVOURITE';
export const REMOVE_FAVOURITE_SAGA='REMOVE_FAVOURITE_SAGA';